### ISSUE TITLE
run local score

### ISSUE THREAD

**Issue by aremazeilles** [CentroEPiaggio/dysturbance#5]
First question, are you  familiar with Githubbased code revision (Merge Request and so on)? This is to see how we should collaborate.

Trying to launch the code, the file run_local_pi mentions a isfall parameter that I don't know what value should be used.
Launching with the value 1, I get the following error (launched from linux terminal):

```term
./run_local_pi tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_run_0_platformData.csv tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_testbed.yaml output 1
current directory: /home/anthony/code/eurobench/dysturbance/Dysturbance_Pi
csv file: tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_run_0_platformData.csv
structure file: tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_testbed.yaml
result dir: output
the system is fallen: 1 
parse error near line 17 of file /home/anthony/code/eurobench/dysturbance/Dysturbance_Pi/src/Compute_Local_PI.m

  syntax error

>>> Experiment_folder = strcat("tests\",result_folder,"\",name);
                                                                 ^

error: called from
    ./run_local_pi at line 26 column 1
``` 

It seems parameter `isfall`is not an input parameter of function `ComputeLocalPI`. So should this parameter be maintained?
Could you comment on the puprpose of the line 16 of file `Compute_Local_PI.m`? 
The spirit we try to get is that:

* the computation is done on all the files provided as input (explictely named, as you do for file platformdata and tesbed)
* all results are store in the folder name provided as last parameter.

Do you think the code could be changed in that way?

**Comment by aremazeilles** [comment]
Ping

**Comment by simomonte** [comment]
Hi Anthony, 
in the late version of the Compute_Local_PI, we decide to insert the isfall boolean directly inside the raw_input_data file, so that you do not need to remember which experiment leads to a fall, and which resist. The structure now asks if the robot falls at the end of the experiment, and saves a boolean inside the raw data files.
That is done since we saw, during experiments, that remembering all the results from (e.g. 1200) tests was a lot way harder than insert the result after each test. 
I am sorry I forgot to update the run_local_PI function too, I am adjusting all these files right now.

**Comment by aremazeilles** [comment]
OK. One done, please update the documentation. The best would be that you indicate there the command to launch the PI metric computation. So that I can copy and paste it on my computer to launch it. 
Also, I may have done an error. I launched the code from `Dysturbance_pi`, but I see you also have a folder `code_pi`. Are the two needed?

**Comment by simomonte** [comment]
No, code_pi is a version that we decide to get rid of and will be deleted soon. We are currently working on updating the whole repository and adjusting the code to work with  Octave.
Anyway, the correct folder with the data processing is Dysturbance_Pi. 
We hope that at the end of the week we can provide the updated version of the code, that will work with octave instead of the current version which works with Matlab, and that will have all the issues solved.
I am sorry for the delay.

**Comment by aremazeilles** [comment]
Ping

**Comment by aremazeilles** [comment]
ping

**Comment by aremazeilles** [comment]
Ping. Could you indicate me when you expect to update this?

Thanks

**Comment by simomonte** [comment]
Hi Anthony! I am scheduling to updating it on Monday/Tuesday.

**Comment by simomonte** [comment]
Hi Anthony! I updated the .md for the Dysturbance_PI folder with all the instructions necessary to test the code. I also provided examples of experimental data. Please check it and let me know if there is any problem with that.
Thank you!

**Comment by aremazeilles** [comment]
Hello
I am not sure to understand how to use the program. I see it quite different from the spirit of what we expect in Eurobench, to insert it in our server.
It seems the initial script I used to launch from a linux terminal ( `./run_local_pi` command at the begining of this thread) disappeared. I undertand you work under windows, but we would be keen in maintaining the linux compatibility, as the automation system from where we would like to execute your code should be a linux machine.

More than the absence of the simple script  `./run_local_pi` what worries more is that it seems the type of input parameters changed. Before, we had an explicit naming of the needed files, I assume as relative path.
Now it seems that the last parameter of the local_pi is a folder, where should be read the data. Is that correct?

I'll send you an email to set a meeting slot.

Finally, I think it is not a good practice to place all experimental data aside the code. Now it seems the repository is around 4Go. I think it is better to place elswhere experimental data, and only let in the code folder subset of it (1 run or 2) that can be used to verify the computation outcome.

**Comment by aremazeilles** [comment]
Close this one, as outdated.
